### ISSUE TITLE
Consumer not able to read kafka topic and write to HDFS

### ISSUE THREAD

**Issue by sbellary300s** [dibbhatt/kafka-spark-consumer#47] opened 2017-06-22 15:35 UTC
The kafka-spark-consumer (v.1.0.6) job was reading kafka topic and writing to couchbase successfully on CDH 5.5.1 Cluster. But it is not reading or writing the data after we upgraded to CDH 5.9.0. Additionally we are also trying to write to HDFS along with Couchbase. The job just creates specified directories in HDFS and keeps running forever but does not read or write anything. 
Specs:
kafka version: 0.8.2.0 
Zookeeper version: zookeeper-3.4.5+cdh5.9.0+98 
spark version: spark-1.6.0+cdh5.9.0+229 

pom.xml : 
<dependency> 
<groupId>dibbhatt</groupId> 
<artifactId>kafka-spark-consumer</artifactId> 
<version>1.0.6</version> 
</dependency> 

We also tried to use latest version  v1.0.7  but it didnt help.

Thanks
Srikanth

**Comment by dibbhatt** [comment] 2017-06-22 15:55
Can you please share Logs of the consumer .

What happened when you restart the job ? It fetching Zero messages ? 

Is there any difference between Kafka or Spark version between CDH upgrade ?

If I look at the logs, I will be able to tell something about the issue.

**Comment by sbellary300s** [comment] 2017-06-22 16:01
Hello, thanks for your prompt response, can you please share your email id so that i can share my logs?

**Comment by krishna383** [comment] 2017-06-26 19:17
@dibbhatt We are observing that the offset is not getting committed to zookeeper. We are not seeing the consumerid in the zkcli

**Comment by dibbhatt** [comment] 2017-06-29 05:55
Did you tried running kafka console consumer from Spark Exeutor and see if it able to consume messages ? You are not seeing offsets in ZK mean consumer is not consuming . Can you share the properties files will all consumer specific properties you specified ?

**Comment by dibbhatt** [comment] 2017-07-07 04:30
Are you still seeing the issue ? If not you can close the ticket.

**Comment by dibbhatt** [comment] 2017-07-18 00:16
hi @sbellary300s  @krishna383  if the issue is fixed, please close this ticket.

**Comment by dibbhatt** [comment] 2017-07-21 21:50
closing this as I have not heard anything yet @sbellary300s . if you still having the issue, please let me know more details about the the same.

**Closed by dibbhatt** 2017-07-21 21:50 UTC
